export const GET_lIST_MOVIE_STARTED = "GET_lIST_MOVIE_STARTED";
export const GET_lIST_MOVIE_SUCCESS = "GET_lIST_MOVIE_SUCCESS";
export const GET_lIST_MOVIE_FAILURE = "GET_lIST_MOVIE_FAILURE";
export const SEARCH_LIST_MOVIE_STARTED = 'SEARCH_LIST_MOVIE_STARTED';
export const SEARCH_LIST_MOVIE_SUCCESS = 'SEARCH_LIST_MOVIE_SUCCESS';
export const SEARCH_LIST_MOVIE_FAILURE = 'SEARCH_LIST_MOVIE_FAILURE';